Queen's Crown changed to King's Crown logo in Header
UKGovernmentBEIS/govuk-design-system-dotnet pull request #16
Opened 2024-03-13 16:51 UTC by Glenn-Clarke

Changed the Queen's Crown in the header to the King's Crown. 

The SVG and fallback path have been changed in line with: [GovUk Frontend release notes](https://github.com/alphagov/govuk-frontend/releases/tag/v4.8.0)

This also requires assets from the V4.8.0 release of the GovUkFrontend library.

2024-03-14 09:26 UTC, DanCorderSoftwire requested changes

2024-03-14 09:26 UTC, DanCorderSoftwire commented on README.md
> +This library currently works with GOV.UK Frontend v4.8.0.
I think this needs to be a bit stronger - presumably if someone uses a version less than 4.8.0 and updates our library then the crown logo on their site will break. So I think we need something like `(and requires at least v4.8.0)` on this line.
Also please add a `Breaking change` section below to explain this a bit more.

2024-03-15 09:14 UTC, DanCorderIPV approved these changes

2024-03-15 09:14 UTC, DanCorderIPV commented on README.md
> +This library currently works with GOV.UK Frontend v4.8.0 (and requires v4.8.0.)
I'd say "at least" here

2024-03-15 09:15 UTC, DanCorderSoftwire approved these changes

2024-03-15 09:24 UTC, merged